UserManager-web/src/main/java/login/DataBean.java
package login;

import java.io.Serializable;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;

import enumerations.Role;

@ManagedBean
@ApplicationScoped
public class DataBean implements Serializable {
	private static final long serialVersionUID = 1L;

	public Role[] getRoles() {
		return Role.values();
		}
	}

UserManager-web/src/main/webapp/pages/admin/welcome.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/template/template.xhtml">

	<ui:param name="page_name" value="Accueil" />
	<ui:define name="content">
		<h:panelGroup columns="2">
			<h:form>
				<table>
					<tr>
						<td><h:outputText value="Login (Email)"></h:outputText></td>
						<td><h:inputText value="#{userBean.email}"></h:inputText></td>
					</tr>
					<tr>
						<td><h:outputText value="Mot de Passe"></h:outputText></td>
						<td><h:inputSecret value="#{userBean.password}"></h:inputSecret></td>
					</tr>
					<tr>
						<td><h:outputText value="Nom"></h:outputText></td>
						<td><h:inputText value="#{userBean.firstname}"></h:inputText></td>
					</tr>
					<tr>
						<td><h:outputText value="Prenom"></h:outputText></td>
						<td><h:inputText value="#{userBean.lastname}"></h:inputText></td>
					</tr>
					<tr>
						<td><h:outputText value="Actif / Inactif"></h:outputText></td>
						<td><h:selectBooleanCheckbox value="#{userBean.isActif}"></h:selectBooleanCheckbox></td>
					</tr>
					<tr>
						<td><h:outputText value="Role"></h:outputText></td>
						<td><h:selectOneMenu value="#{userBean.role}">
								<f:selectItem itemLabel="Choisir Role" itemValue="" />
								<f:selectItems value="#{dataBean.roles}" />
							</h:selectOneMenu></td>
					</tr>
					<tr>
						<td colspan="2"><h:commandButton value="Ajouter Employé"
								action="#{userBean.addUser()}" /></td>
					</tr>
				</table>
			</h:form>
		</h:panelGroup>
		<h:panelGroup columns="2">
			<h:form>
				<h:dataTable value="#{userBean.users}" var="user" border="1">
					<h:column>
						<f:facet name="header">
							<h:outputText value="Login" />
						</f:facet>
						<h:outputText value="#{user.email}" />
					</h:column>
					<h:column>
						<f:facet name="header">
							<h:outputText value="Last Name" />
						</f:facet>
						<h:outputText value="#{user.lastname}" />
					</h:column>
					<h:column>
						<f:facet name="header">
							<h:outputText value="First Name" />
						</f:facet>
						<h:outputText value="#{user.firstname}" />
					</h:column>
					<h:column>
						<f:facet name="header">
							<h:outputText value="Role" />
						</f:facet>
						<h:outputText value="#{user.role}" />
					</h:column>
					<h:column>
						<f:facet name="header">
							<h:outputText value="Actif" />
						</f:facet>
						<h:outputText value=" #{user.activ == true ? 'Oui' : 'Non'}" />
					</h:column>
					<h:column>
						<f:facet name="header">
							<h:outputText value="Action" />
						</f:facet>
						<h:commandButton action="#{userBean.deleteUser(us.id)}"
							value="Supprimer" />
					</h:column>
				</h:dataTable>
			</h:form>
		</h:panelGroup>
		<h:panelGroup>
			<h:form>
				<h:outputText
					value="Bonjour #{loginBean.user.firstname} #{loginBean.user.lastname}" /> |
<h:commandLink value="Déconnexion" action="#{loginBean.doLogout()}" />
			</h:form>
		</h:panelGroup>
	</ui:define>
</ui:composition>